config/routes.rb
Flashcards::Application.routes.draw do
  root to: "homes#index"
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :decks do
    resources :cards, except: :index
  end
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :deck
  attr_accessible :back, :front
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  has_many :cards
  belongs_to :user
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :decks
  attr_accessible :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user
  helper_method :signed_in?

  def current_user
    if cookies[:user_id]
      user_id = cookies.signed[:user_id]
      User.find_by_id(user_id)
    end
  end

  def sign_in user
    cookies.signed[:user_id] = user.id
  end

  def authenticate
    unless signed_in?
      redirect_to new_session_path
    end
  end

  def signed_in?
    current_user
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_filter :authenticate

  def show
    @deck = find_deck
    @card = find_card(@deck)
  end

  def new
    @deck = find_deck
    @card = @deck.cards.new
  end

  def create
    @deck = find_deck
    @card = @deck.cards.new(params[:card])
    @card.save
    redirect_to @deck
  end

  def edit
    @deck = find_deck
    @card = find_card(@deck)
  end

  def update
    @deck = find_deck
    @card = find_card(@deck)
    @card.update_attributes(params[:card])
    redirect_to @deck
  end

  def destroy
    @deck = find_deck
    @card = find_card(@deck)
    @card.destroy
    redirect_to @deck
  end

  private

  def find_deck
    current_user.decks.find(params[:deck_id])
  end

  def find_card deck
    deck.cards.find(params[:id])
  end

end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_filter :authenticate

  def index
    @decks = current_user.decks
  end

  def show
    @deck = find_deck
    @cards = @deck.cards
  end

  def new
    @deck = current_user.decks.new
  end

  def create
    @deck = current_user.decks.new(params[:deck])

    if @deck.save
      redirect_to decks_url, notice: 'Decks was successfully created.'
    else
      render action: "new"
    end
  end

  def edit
    @deck = find_deck
  end

  def update
    @deck = find_deck
    if @deck.update_attributes(params[:deck])
      redirect_to decks_url, notice: 'The deck was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @deck = find_deck
    @deck.destroy
    redirect_to decks_url, notice: 'The deck has been successfully deleted.'
  end

  private

  def find_deck
    current_user.decks.find(params[:id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user
      sign_in(user)
      redirect_to decks_path
    else
      redirect_to new_user_path, notice: "Please sign up first."
    end
  end

  def destroy
    cookies.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.save
    sign_in @user
    redirect_to decks_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/views/cards/_form.html.erb
          <%= f.label :front %>
          <%= f.text_field :front %>
          <%= f.label :back %>
          <%= f.text_field :back %>

app/views/cards/edit.html.erb
<%= form_for([@deck, @card]) do |f| %>
  <div class="row">
    <div class="small-12 columns">
      <fieldset>
        <legend> Card </legend>
          <%= render 'form', f: f %>
          <%= f.submit "Update Card", :class => "small button success radius" %>
          <%= link_to "Cancel", deck_url(@deck), :class => "small button secondary radius" %>
      </fieldset>
    </div>
  </div>
<% end %>

app/views/cards/new.html.erb
<%= form_for([@deck, @card]) do |f| %>
  <div class="row">
    <div class="small-12 columns">
      <fieldset>
        <legend> Card </legend>
          <%= f.label :front %>
          <%= f.text_field :front %>
          <%= f.label :back %>
          <%= f.text_field :back %>
          <%= f.submit "Create Card", :class => "small button success radius" %>
          <%= link_to "Cancel", deck_url(@deck), :class => "small button secondary radius" %>
      </fieldset>
    </div>
  </div>
<% end %>

app/views/cards/show.html.erb
<%= title @cardback %>
<div class="row">
  <div class="small-12 columns">
    <fieldset>
    <legend>Back</legend>
    <p> <%= @card.back %> </p>
    <p> <%= @card.front %> </p>
      <%= link_to "Back", @deck, :class => "small button secondary radius" %><br />
    </fieldset>
  </div>
</div>

app/views/decks/_form.html.erb
<%= form_for @deck do |f| %>
<div class="row">
 <div class="small-12 columns">
   <fieldset>
    <legend> Deck </legend>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.submit "New Deck", :class => "small button success radius" %>
      <%= link_to "Cancel", decks_url, :class => "small button secondary radius" %>
   </fieldset>
  </div>
</div>
<% end %>

app/views/decks/edit.html.erb
<%= render :partial => 'form' %>

app/views/decks/index.html.erb
<% title "Furashcaado App" %>
<div class="row">
  <div class="small-12 columns">
    <h1>Decks</h1>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <p>
    <%= link_to "New Deck", new_deck_url, :class => "small button success radius" %>
  </div>
</div>
<div class="row">
  <fieldset>
    <legend>Choose a Language</legend>
    <% @decks.each do |deck| %>
    <div class="small-8 columns"><%= link_to deck.name, deck_url(deck.id) %></div>
    <div class="small-4 columns" style="text-align:right;">
      <%= link_to "Edit",
                   edit_deck_url(deck.id),
                   :class => "tiny button radius" %>
      <%= link_to "Delete",
                   deck_url(deck.id),
                   method: :delete,
                   data: { confirm: 'Are you sure?' },
                   :class => "tiny button alert radius" %>
    </div>
  <% end %>
  </fieldset>
</div>

app/views/decks/new.html.erb
<%= render :partial => 'form' %>

app/views/decks/show.html.erb
<%= title @deck.name %>
<div class="row">
  <div class="small-12 columns">
    <fieldset>
    <%= link_to "New Card", new_deck_card_url(@deck), :class => "small button success radius" %><br />
    <legend>Front</legend>
    <h3> <%= @deck.name %> </h3>
      <% @cards.each do |card| %>
        <div class="small-8 columns"><%= link_to card.front, [@deck, card] %></div>
        <div class="small-4 columns" style="text-align:right;">
          <%= link_to "Edit",
                       edit_deck_card_url(@deck, card),
                       :class => "tiny button radius" %>
          <%= link_to "Delete",
                       [@deck, card],
                       method: :delete,
                       data: { confirm: 'Are you sure?' },
                       :class => "tiny button alert radius" %>
        </div>
      <% end %>
    </ul>
      <%= link_to "Decks", decks_url, :class => "small button secondary radius" %>
    </fieldset>
  </div>
</div>

app/views/homes/index.html.erb
<h2>Welcome to the furashcaado app.</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <div class="container">

    <div class="row">
      <div class="small-12 columns">
        <% flash.each do |name, msg| %>
          <a href="#" class="close">&times;</a>
          <div data-alert class="div alert-box <%= name == :notice ? "success" : "alert" %> round">
            <%= msg %>
          </div>
        <% end %>
      </div>
      <div class="small-12 columns" style="text-align:right;">
        <span>
          <% if signed_in? %>
            Welcome <%= current_user.email %>
            <%= link_to "Sign out", session_url, method: :delete %>
          <% else %>
            <%= link_to "Sign Up", new_user_path %>
            <%= link_to "Sign in", new_session_path %>
          <% end %>
        </span>
      </div>
    </div>

    <div class="row">
      <div class="small-12 columns">
        <%= yield %>
      </div>
    </div>

  </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <div class="row">
    <div class="small-12 columns">
      <fieldset>
        <legend> New User </legend>
          <%= f.label :email %>
          <%= f.text_field :email %>
          <%= f.submit "Sign up", :class => "small button success radius" %>
      </fieldset>
    </div>
  </div>
<% end %>